sync:
  defaults:
    ignore:
      vcs: true
      paths:
        - node_modules
        - .pnpm-store
        - .yarn
        - dist
        - build
        - .next
        - .nuxt
        - .turbo
        - target
        - .venv
        - __pycache__
        - .cache
        - .git