repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9  # 예시: 프로젝트에 맞게 고정
    hooks:
      - id: ruff-check
        args: [--fix]     # (1) 린트 & 자동수정 (import 정렬 포함)
      - id: ruff-format   # (2) 포매터 (항상 ruff-check 뒤)
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: []             # ★ Ruff 포매터 쓰면 비워두거나 제거 (혼용 금지)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-q", "-r", "."]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
        args: ["-r", "requirements.txt"]
        stages: [manual]  # 커밋마다 느리면 수동/CI에서만 실행